version: "3"
# Actually we only need to open the ports for the frontend when using Docker-compose.
# However, when converting this file to Kubernetes yaml files with `kompose.io`,
# the rest of the services will not be created unless we have specified the ports.
# in a real production scenario we would create one yml for docker-compose without the rest of the ports
# and one for the convertsion with `kompose.io`
services:
  mysql:
    image: victorrgez/cloudprojectirismysql
    container_name: mysql
    ports:
      - 0.0.0.0:3306:3306
    volumes:
      - statefuldatabase:/var/lib/mysql
  model:
    image: victorrgez/cloudprojectirismodel
    container_name: model
    ports:
      - 0.0.0.0:3000:3000
  frontend:
    image: victorrgez/cloudprojectirisfrontend
    container_name: frontend
    ports:
      - 0.0.0.0:5000:5000
  backend:
    image: victorrgez/cloudprojectirisbackend
    container_name: backend
    depends_on:
      - model
      - mysql
    ports:
      - 0.0.0.0:8080:8080
    restart: always
volumes:
  statefuldatabase:
