apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: model
  name: model
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: model
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: model
    spec:
      containers:
        - image: victorrgez/cloudprojectirismodel
          name: model
          ports:
            - containerPort: 3000
          resources: {}
      restartPolicy: Always
status: {}
