name: CI/CD pipeline
on:
  push:
    branches:
      - main
      - cicd
jobs:
  RunTests:
    runs-on: ubuntu-latest
    container:
      image:
        python:3.9-slim
    steps:
      - name: Copy repo files to container
        uses: actions/checkout@v3
      - name: Install test dependencies
        run: pip3 install -r tests/requirements.txt
      - name: Run tests
        run: pytest -v
      - run: echo "All tests run succesfully"