name: CI/CD pipeline
on:
  push:
    branches:
      - main
      - cicd
jobs:
  RunFrontBackTests:
    runs-on: ubuntu-latest
    container:
      image:
        python:3.9-slim
    steps:
      - name: Copy repo files to container
        uses: actions/checkout@v3
      - name: Install test dependencies
        run: pip3 install -r tests/requirements.txt
      - name: Run tests
        # Ignores other tests that are run in different jobs with other requirements:
        run: pytest -v --ignore=tests/test_irismodel.py --ignore=tests/test_integrationMySQL.py
      - run: echo "All Frontend/Backend tests run succesfully"
  RunModelTests:
    runs-on: ubuntu-latest
    container:
      image:
        python:3.9-slim
    steps:
      - name: Copy repo files to container
        uses: actions/checkout@v3
      - name: Install test dependencies
        run: pip3 install -r tests/irismodelrequirements.txt
      - name: Run tests
        # The following flag gets rids of the deprecation warning of "Imp" module:
        run: pytest -v -W ignore::DeprecationWarning tests/test_irismodel.py
      - run: echo "All Model tests run succesfully"
  RunMySQLIntegrationTests:
    runs-on: ubuntu-latest
    steps:
      - name: Copy repo files to container
        uses: actions/checkout@v3
      - name: Build MySQL image
        run: docker build -t mysqlimage src/mysql3306
      - name: Run MySQL image in the background
        run: docker run -d --rm --name mysql -p=0.0.0.0:3306:3306 mysqlimage
      - name: Install dependences
        run: pip3 install -r tests/requirements.txt
      - name: Run Integrationt tests
        run: pytest -v tests/test_integrationMySQL.py